[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
actix-service = "2"
actix-cors = "0.6.1"
dotenv = "0.15.0"
sea-orm = { version = "^0.7", features = [ "sqlx-postgres", "runtime-actix-native-tls", "macros", "mock" ], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "0.8"
tracing = "0.1"
tracing-subscriber = "0.2"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
actix-web-httpauth = "0.6.0"
derive_more = "0.99.17"
jsonwebtoken = "8.0.1"
async-trait = "0.1.52"
mockall = "0.11.0"
futures-util = "0.3.21"
tokio = { version = "1", features = ["full"] }
