[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
dotenv = "0.15.0"
sea-orm = { version = "^0.6", features = [ "sqlx-postgres", "runtime-actix-native-tls", "macros" ], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "0.8"
tracing-subscriber = "0.3.9"
