[package]
name = "rust_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-service = "2"
actix-cors = "0.6.1"
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.17"
sea-orm = { version = "^0.7", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "mock" ], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "0.8"
tracing = "0.1"
tracing-subscriber = "0.2"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
actix-web-httpauth = "0.6.0"
derive_more = "0.99.17"
jsonwebtoken = "8.0.1"
async-trait = "0.1.52"
mockall = "0.11.0"
futures-util = "0.3.21"
anyhow = { version = "1.0.57", features = ["backtrace"] }
thiserror = "1.0.31"
tokio = { version = "1", features = ["full"] }
async-mutex = "1.4.0"
