x-app-environment: &app-environment
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  DB_USER: $DB_USER
  DB_NAME: $DB_NAME
  DB_PASSWORD: $DB_PASSWORD
  DB_SSL: $DB_SSL
  PORT: $PORT
  AUTH0_DOMAIN: $AUTH0_DOMAIN
  AUTH0_AUDIENCE: $AUTH0_AUDIENCE
  ALLOWED_ORIGINS: $ALLOWED_ORIGINS
  ENCRYPTION_KEY: $ENCRYPTION_KEY

x-db-environment: &db-environment
  DB_SSL_MODE: $DB_SSL_MODE
  DB_HOST: $DB_HOST
  DB_PORT: $DB_PORT
  DB_USER: $DB_USER
  DB_NAME: $DB_NAME
  DB_PASSWORD: $DB_PASSWORD
  DB_DROP: $DB_DROP
  SEEDER_DIR: $SEEDER_DIR
  PGPASSWORD: $DB_PASSWORD

services:
  run:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "${PORT:-7000}:${PORT:-7000}"
    environment: *app-environment

  build:
    image: rust:latest
    command: "cargo build --release"
    working_dir: /app
    volumes:
      - ./:/app

  test:
    image: rust:latest
    command: "cargo test"
    working_dir: /app
    volumes:
      - ./:/app
    environment: *app-environment

  ci:
    build:
      context: .
      dockerfile: Dockerfile.ci
    working_dir: /app
    volumes:
      - ./:/app

  postgres:
    image: postgres:12.7
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - dbdata_12.7:/var/lib/postgresql/data

  db-init:
    command: "sh -c /app/dbinit.sh"
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment: *db-environment

  db-migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    environment: *db-environment

  db-seed:
    command: "sh -c /app/dbseed.sh"
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment: *db-environment

volumes:
  dbdata_12.7:
